/**
 * TADS ad network adapter (Rewarded Ads).
 *
 * The SDK is loaded lazily on the first ad request so it never slows down the
 * Mini App boot. Because publishers get slightly different snippets from the
 * TADS dashboard, the adapter probes the known script URLs and then the known
 * API surfaces (`show_<widgetId>()`, `TelegramAdsController`, `window.tads`),
 * using whichever one the loaded SDK actually exposes.
 *
 * If TADS gave you a different snippet in your dashboard, add its URL to
 * SDK_URLS (first entry wins) — no other change is required.
 */

const SDK_URLS = [
  "https://cdn.tads.pro/sdk/tads-sdk.js",
  "https://static.tads.pro/tads-sdk.js",
  "https://cdn.tadsapp.com/tads-sdk.js",
];

export interface TadsResult {
  ok: boolean;
  error?: string;
}

let loadPromise: Promise<boolean> | null = null;
let controller: any = null;

function loadScript(src: string): Promise<boolean> {
  return new Promise((resolve) => {
    const existing = document.querySelector<HTMLScriptElement>(`script[data-tads="${src}"]`);
    if (existing) {
      if (existing.dataset.loaded === "1") return resolve(true);
      existing.addEventListener("load", () => resolve(true), { once: true });
      existing.addEventListener("error", () => resolve(false), { once: true });
      return;
    }
    const s = document.createElement("script");
    s.src = src;
    s.async = true;
    s.dataset.tads = src;
    s.addEventListener("load", () => { s.dataset.loaded = "1"; resolve(true); }, { once: true });
    s.addEventListener("error", () => resolve(false), { once: true });
    document.head.appendChild(s);
  });
}

/** Loads the TADS SDK once and initializes the controller for this widget. */
async function ensureSdk(widgetId: string): Promise<boolean> {
  if (loadPromise) return loadPromise;
  loadPromise = (async () => {
    for (const url of SDK_URLS) {
      const ok = await loadScript(url);
      if (!ok) continue;
      const w = window as any;
      try {
        if (typeof w.TelegramAdsController === "function") {
          controller = new w.TelegramAdsController();
          controller.initialize?.({ pubId: widgetId, appId: widgetId, widgetId });
        } else if (w.TelegramAdsController) {
          controller = w.TelegramAdsController;
          controller.initialize?.({ pubId: widgetId, appId: widgetId, widgetId });
        } else if (w.tads?.init) {
          controller = w.tads.init({ widgetId });
        } else if (w.Tads?.init) {
          controller = w.Tads.init({ widgetId });
        }
      } catch {
        controller = null;
      }
      if (controller || typeof w[`show_${widgetId}`] === "function") return true;
    }
    return false;
  })();
  return loadPromise;
}

/**
 * Shows a TADS rewarded ad and resolves once the user has finished watching it.
 * Never throws — always resolves with `{ ok }` so the caller can decide whether
 * to grant the reward.
 */
export async function showTadsRewarded(widgetId: string): Promise<TadsResult> {
  if (!widgetId) return { ok: false, error: "no_widget" };
  const w = window as any;

  const ready = await ensureSdk(widgetId);
  if (!ready) return { ok: false, error: "sdk_unavailable" };

  const call = (fn: any, thisArg: any, args: any[] = []) => {
    try {
      return Promise.resolve(fn.apply(thisArg, args));
    } catch (e: any) {
      return Promise.reject(e);
    }
  };

  try {
    // 1) Per-widget global generated by the TADS snippet: show_11349()
    const perWidget = w[`show_${widgetId}`];
    if (typeof perWidget === "function") {
      await call(perWidget, w);
      return { ok: true };
    }

    // 2) Controller-style API
    if (controller) {
      const method =
        controller.triggerRewardedVideo ||
        controller.showRewardedVideo ||
        controller.showRewarded ||
        controller.show;
      if (typeof method === "function") {
        const res: any = await call(method, controller, [{ widgetId }]);
        if (res && res.done === false) return { ok: false, error: "closed" };
        if (res && res.error) return { ok: false, error: String(res.error) };
        return { ok: true };
      }
    }

    return { ok: false, error: "sdk_unavailable" };
  } catch (e: any) {
    const msg = typeof e === "string" ? e : e?.description || e?.message || "failed";
    return { ok: false, error: String(msg) };
  }
}
