export const alertsDict: Record<string, string> = {
  "Не удалять": "Do not delete",
  "1 день": "1 day",
  "3 дня": "3 days",
  "7 дней": "7 days",
  "14 дней": "14 days",
  "30 дней": "30 days",
  "Не ограничивать": "No limit",
  "Последние 100": "Last 100",
  "Последние 500": "Last 500",
  "Последние 1000": "Last 1000",
  "Последние 5 000": "Last 5,000",
  "Последние 10 000": "Last 10,000",
  "Видеореклама": "Video ad",
  "Видео": "Video",
  "Подписка": "Subscription",
  "Просмотр поста": "Post view",
  "Пост": "Post",
  "Просмотр истории": "Story view",
  "История": "Story",
  "Реакция": "Reaction",
  "Опрос": "Survey",
  "Обнуление баланса": "Balance reset",
  "Обнуление": "Reset",
  "Промокод": "Promo code",
  "Промо": "Promo",
  "Вывод выполнен": "Withdrawal completed",
  "Вывод": "Withdrawal",
  "Вывод отменён": "Withdrawal rejected",
  "Все логи": "All logs",
  "Логи промокодов": "Promo code logs",
  "Поиск по ID (v100000000, r100000000…)": "Search by ID (v100000000, r100000000…)",
  "Поиск по @username или telegram_id": "Search by @username or telegram_id",
  "Все": "All",
  "По дням": "By days",
  "По кол-ву": "By count",
  "Хранить": "Keep",
  "Автоочистка отключена.": "Auto-cleanup disabled.",
  "Логи хранятся без ограничений — ничего не удаляется автоматически.": "Logs are kept without limits — nothing is deleted automatically.",
  "Автоочистка включена:": "Auto-cleanup enabled:",
  "удаляются записи старше": "entries older than",
  "дн.": "days",
  "хранятся только последние": "only the last",
  "записей": "entries are kept",
  "Экспорт в CSV": "Export to CSV",
  "Пока нет записей": "No entries yet",
  "Задание удалено": "Task deleted",
  "Промо удалено": "Promo deleted",
  "Рекламодатель удалён": "Advertiser deleted",
  "Пользователь": "User",
  "Тип": "Type",
  "ID задания": "Task ID",
  "Название / Причина": "Title / Reason",
  "да": "yes",
  "нет": "no",
  "Рекламодатель": "Advertiser",
  "ID рекламодателя": "Advertiser ID",
  "Начало просмотра": "View start",
  "Окончание просмотра": "View end",
  "Время": "Time",
  "Списание (PT)": "Deduction (PT)",
  "Награда (PT)": "Reward (PT)",
  "Удалён": "Deleted",
  "Автоочистка отключена": "Auto-cleanup disabled",
  "Хранить последние": "Keep the last",
  "Автоочистка по дням отключена": "Day-based auto-cleanup disabled",
  "Лимит по количеству снят": "Count limit removed",
  "Поиск по промокоду...": "Search by promo code...",
  "Поиск по @username...": "Search by @username...",
  "Логи не удаляются автоматически": "Logs are not deleted automatically",
  "Логи старше": "Logs older than",
  "дн. удаляются автоматически": "days are deleted automatically",
  "Активаций промокодов не найдено": "No promo code activations found",
  "промокод удалён": "promo code deleted",
};
