export const contentDict: Record<string, string> = {
  "0 = не проверять.": "0 = don't check.",
  "1 = один раз, 0 = показывать всегда.": "1 = once, 0 = always show.",
  "ID скопирован": "ID copied",
  "Введите название задания": "Enter task title",
  "Введите название": "Enter title",
  "Видео": "Video",
  "Видеореклама (Mini App)": "Video Ad (Mini App)",
  "Видеореклама": "Video Ad",
  "Вкл. все": "Enable all",
  "Включить все": "Enable all",
  "Все задания включены": "All tasks enabled",
  "Все задания и видеореклама группируются по рекламодателям.": "All tasks and video ads are grouped by advertiser.",
  "Все задания отключены": "All tasks disabled",
  "Все задания удалены": "All tasks deleted",
  "Все": "All",
  "Добавить контент": "Add content",
  "Добавить рекламодателя": "Add advertiser",
  "Если вернулся раньше — задание не засчитывается, кнопка вернётся. Если вернулся во время или позже — задание выполнено.": "If they return earlier, the task is not counted and the button resets. If they return on time or later, the task is completed.",
  "Если отписался — PT списываются, задание возвращается с красной рамкой.": "If they unsubscribed, PT is deducted and the task returns with a red border.",
  "Загрузите медиафайл": "Upload a media file",
  "Задание обновлено": "Task updated",
  "Название (видно пользователям)": "Title (visible to users)",
  "Название": "Name",
  "Например, Coca-Cola": "e.g. Coca-Cola",
  "Например, Подпишись на наш канал": "e.g. Subscribe to our channel",
  "Не удалось загрузить файл": "Failed to upload file",
  "Нет рекламодателей. Создайте первого, чтобы начать.": "No advertisers. Create your first one to get started.",
  "Ничего не найдено": "Nothing found",
  "Новый контент": "New content",
  "Новый рекламодатель": "New advertiser",
  "Откл. все": "Disable all",
  "Отключить все": "Disable all",
  "Открыть": "Open",
  "Переименовать рекламодателя": "Rename advertiser",
  "Переименовать": "Rename",
  "Перейти": "Go",
  "Поиск по ID (например, v100000000) или названию…": "Search by ID (e.g. v100000000) or name…",
  "Посмотреть историю": "View Story",
  "Посмотреть пост": "View Post",
  "Проверка отписки": "Unsubscribe check",
  "Проверка через": "Check after",
  "Редактировать задание": "Edit task",
  "Редактировать": "Edit",
  "Рекламодатели": "Advertisers",
  "Рекламодатель добавлен": "Advertiser added",
  "Рекламодатель обновлён": "Advertiser updated",
  "Рекламодатель удалён": "Advertiser deleted",
  "Рекламодатель": "Advertiser",
  "Сколько раз показать предупреждение об отписке": "How many times to show the unsubscribe warning",
  "Сколько раз пользователь увидит поп-ап о том, что он отписался.": "How many times the user will see the pop-up about unsubscribing.",
  "Сколько секунд пользователь должен пробыть вне Mini App": "How many seconds the user must stay outside the Mini App",
  "Сначала выберите рекламодателя": "Select an advertiser first",
  "Сохранить": "Save",
  "Тип контента": "Content type",
  "У этого рекламодателя пока нет контента.": "This advertiser has no content yet.",
  "Удалит все задания и видеорекламу рекламодателя": "This will delete all tasks and video ads of advertiser",
  "Удалить весь контент?": "Delete all content?",
  "Удалить все": "Delete all",
  "Удалить рекламодателя": "Delete advertiser",
  "Удалить": "Delete",
  "Фото": "Photo",
  "Через сколько бот проверит, что пользователь всё ещё подписан.": "After how long the bot will check that the user is still subscribed.",
  "активных": "active",
  "всего": "total",
  "единиц контента рекламодателя будут удалены безвозвратно.": "content items of the advertiser will be permanently deleted.",
  "единиц контента": "content items",
  "м": "m",
  "мин": "min",
  "с": "s",
  "ч": "h",
};
