export const settingsDict: Record<string, string> = {
  // SettingsPage
  "Курс обмена": "Exchange Rate",
  "Отображается в мини-аппе рядом с балансом (≈ X USDT).": "Shown in the Mini App next to the balance (≈ X USDT).",
  "Минимальный вывод": "Minimum Withdrawal",
  "Минимум USDT": "Minimum USDT",
  "Минимум Stars": "Minimum Stars",
  "Пользователи не смогут отправить заявку на вывод ниже этих сумм.": "Users won't be able to request a withdrawal below these amounts.",

  // PromoCodesSection
  "истёк": "expired",
  "д": "d",
  "ч": "h",
  "м": "m",
  "Введите промокод": "Enter a promo code",
  "Некорректная награда": "Invalid reward",
  "Промокод создан": "Promo code created",
  "Промокод перезапущен": "Promo code restarted",
  "Промокод удалён": "Promo code deleted",
  "Скопировано": "Copied",
  "Скопировать": "Copy",
  "Исчерпан": "Exhausted",
  "На паузе": "Paused",
  "Активен": "Active",
  "за активацию": "per activation",
  "активаций": "activations",
  "осталось": "left",
  "срок истёк": "expired",
  "Возобновить": "Resume",
  "Приостановить": "Pause",
  "Перезапустить": "Restart",
  "Скопировать код": "Copy code",
  "Удалить": "Delete",
  "Удалить промокод": "Delete promo code",
  "Действие необратимо. Активации сохранятся в истории пользователей.": "This action is irreversible. Activations will remain in users' history.",
  "Отмена": "Cancel",
  "Промокоды": "Promo Codes",
  "Начисляют PT пользователям при активации в мини-аппе.": "Grants PT to users when activated in the Mini App.",
  "Новый промокод": "New Promo Code",
  "Код": "Code",
  "Любые буквы, цифры, символы": "Any letters, numbers, symbols",
  "Награда, PT": "Reward, PT",
  "Лимит активаций": "Activation limit",
  "Например, 100": "e.g. 100",
  "Срок действия": "Expiration",
  "минут": "minutes",
  "часов": "hours",
  "дней": "days",
  "Можно выбрать одно из ограничений, оба или ни одного. Если ничего не выбрано — промокод бесконечный (но всё равно": "You can choose one of the limits, both, or none. If nothing is selected, the promo code is unlimited (but still",
  "1 активация на аккаунт": "1 activation per account",
  "). Одинаковые коды создать нельзя.": "). Duplicate codes can't be created.",
  "Создать": "Create",
  "Загрузка…": "Loading…",
  "Промокодов пока нет. Создайте первый.": "No promo codes yet. Create the first one.",
  "Активные": "Active",
  "Исчерпанные": "Exhausted",
};
