export const usersDict: Record<string, string> = {
  "Видеореклама": "Video ad",
  "Подписка": "Subscription",
  "Просмотр поста": "Post view",
  "Просмотр истории": "Story view",
  "Реакция": "Reaction",
  "Обнуление баланса": "Balance reset",
  "Промокод": "Promo code",
  "Вывод выполнен": "Withdrawal paid",
  "Вывод отменён (возврат)": "Withdrawal cancelled (refund)",
  "Обнулить баланс": "Reset balance",
  "Текущий баланс": "Current balance",
  "Причина (необязательно)": "Reason (optional)",
  "Например: подозрительная активность / нарушение правил": "e.g.: suspicious activity / rule violation",
  "Причина попадёт в «Все логи», Алерты, историю транзакций пользователя и экспорт.": "The reason will appear in \"All Logs\", Alerts, the user's transaction history and exports.",
  "Отмена": "Cancel",
  "Обнулить": "Reset",
  "Frozen": "Frozen",
  "В сети сейчас": "Online now",
  "Был(а)": "Last seen",
  "Никогда не заходил(а)": "Never logged in",
  "Разбан": "Unban",
  "Бан": "Ban",
  "Разморозить": "Unfreeze",
  "Заморозить": "Freeze",
  "Капча": "Captcha",
  "Сообщение": "Message",
  "Баланс": "Balance",
  "заморожен": "frozen",
  "Топ по балансу": "Balance rank",
  "из": "of",
  "Топ рефералов": "Referral rank",
  "Топ промокодеров": "Promo code rank",
  "шт.": "pcs.",
  "Транзакции": "Transactions",
  "Выводы": "Withdrawals",
  "Алерты": "Alerts",
  "Рефералы": "Referrals",
  "Данные": "Info",
  "Транзакций пока нет": "No transactions yet",
  "Промо удалено": "Promo deleted",
  "Заявок на вывод не было": "No withdrawal requests yet",
  "Оплачено": "Paid",
  "Отменено": "Cancelled",
  "В ожидании": "Pending",
  "Причина": "Reason",
  "Алертов по этому пользователю нет": "No alerts for this user",
  "Всего рефералов": "Total referrals",
  "Всего заработано с рефералов": "Total earned from referrals",
  "Приглашённых пока нет": "No invitees yet",
  "заработано с него": "earned from them",
  "Внутренний ID": "Internal ID",
  "Регистрация": "Registered",
  "Ежедневный бонус": "Daily bonus",
  "Кол-во капч": "Captcha count",
  "Нарушений": "Violations",
  "TON кошелёк": "TON wallet",
  "Копировать": "Copy",
  "IP-адреса": "IP addresses",
  "Ферма: ещё {n} акк(а) с этого IP": "Farm: {n} more account(s) from this IP",
};
